/**
 * WO-122 — the single, guarded service-worker registrar for VeggieMeet.
 *
 * There is exactly one production service worker (`/sw.js`, generated by
 * vite-plugin-pwa / Workbox) and exactly one place that registers it: this
 * module. `injectRegister: null` keeps the plugin from injecting a competing
 * registration.
 *
 * Registration is refused — and any matching stale registration is removed —
 * in development, inside iframes, in Lovable preview hosts, and when the URL
 * carries `?sw=off` (kill switch). That prevents a browser-held worker from
 * ever serving stale HTML in the editor preview.
 *
 * Updates are applied safely: the generated worker uses skipWaiting +
 * clientsClaim, so a new release takes over without a forced reload mid-form.
 */
const SW_URL = "/sw.js";

function isPreviewHost(hostname: string): boolean {
  return (
    hostname.startsWith("id-preview--") ||
    hostname.startsWith("preview--") ||
    hostname === "lovableproject.com" ||
    hostname.endsWith(".lovableproject.com") ||
    hostname === "lovableproject-dev.com" ||
    hostname.endsWith(".lovableproject-dev.com") ||
    hostname === "beta.lovable.dev" ||
    hostname.endsWith(".beta.lovable.dev")
  );
}

async function unregisterMatching(): Promise<void> {
  try {
    const registrations = await navigator.serviceWorker.getRegistrations();
    await Promise.allSettled(
      registrations
        .filter((r) => {
          const url =
            r.active?.scriptURL || r.waiting?.scriptURL || r.installing?.scriptURL || "";
          return url.endsWith(SW_URL);
        })
        .map((r) => r.unregister()),
    );
  } catch {
    // Never let cleanup break app boot.
  }
}

export function registerServiceWorker(): void {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;

  const inIframe = window.self !== window.top;
  const killSwitch = new URLSearchParams(window.location.search).get("sw") === "off";
  const refuse =
    !import.meta.env.PROD ||
    inIframe ||
    killSwitch ||
    isPreviewHost(window.location.hostname);

  if (refuse) {
    void unregisterMatching();
    return;
  }

  window.addEventListener("load", () => {
    navigator.serviceWorker.register(SW_URL).catch(() => {
      // A failed registration must never degrade the app; it simply stays
      // network-only for this session.
    });
  });
}
