// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-upcoming-meetups.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function currentProfileId(supabase, _authUserId) {
  const { data } = await supabase.rpc("get_my_profile");
  const row = Array.isArray(data) ? data[0] : data;
  return row?.id ?? null;
}

// src/lib/mcp/tools/list-upcoming-meetups.ts
var list_upcoming_meetups_default = defineTool({
  name: "list_upcoming_meetups",
  title: "List upcoming meetups",
  description: "List upcoming VeggieMeet meetups the signed-in user can see, ordered by date. Optionally filter by city.",
  inputSchema: {
    city: z.string().optional().describe("Optional city name to filter meetups (e.g. 'Berlin')."),
    limit: z.number().int().optional().describe("Max meetups to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ city, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    let q = supabase.from("meetups").select(
      "id, title, description, category, date, start_time, end_time, capacity, status, custom_location_name, custom_location_address, host_id"
    ).gte("date", today).order("date", { ascending: true }).limit(Math.min(Math.max(limit ?? 20, 1), 50));
    const { data, error } = await q;
    if (error) {
      return {
        content: [{ type: "text", text: `Failed to fetch meetups: ${error.message}` }],
        isError: true
      };
    }
    let rows = data ?? [];
    if (city && city.trim()) {
      const c = city.trim().toLowerCase();
      rows = rows.filter(
        (r) => (r.custom_location_address ?? "").toLowerCase().includes(c) || (r.custom_location_name ?? "").toLowerCase().includes(c)
      );
    }
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { meetups: rows }
    };
  }
});

// src/lib/mcp/tools/get-meetup.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_meetup_default = defineTool2({
  name: "get_meetup",
  title: "Get meetup details",
  description: "Get a single VeggieMeet meetup by id, including host, location, capacity, and current attendee count.",
  inputSchema: {
    meetup_id: z2.string().describe("The meetup id (UUID).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ meetup_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("meetups").select(
      "id, title, description, category, date, start_time, end_time, capacity, status, custom_location_name, custom_location_address, host_id"
    ).eq("id", meetup_id).maybeSingle();
    if (error || !data) {
      return {
        content: [
          { type: "text", text: `Meetup not found or not visible.` }
        ],
        isError: true
      };
    }
    const { count } = await supabase.from("attendance").select("id", { count: "exact", head: true }).eq("meetup_id", meetup_id).eq("status", "joined");
    const [host] = (await supabase.from("profiles").select("id, display_name, current_city").eq("id", data.host_id).limit(1)).data ?? [];
    const result = {
      ...data,
      attendee_count: count ?? 0,
      host: host ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-my-meetups.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_meetups_default = defineTool3({
  name: "list_my_meetups",
  title: "List my meetups",
  description: "List the meetups the signed-in VeggieMeet user is hosting or attending.",
  inputSchema: {
    role: z3.enum(["hosting", "attending", "all"]).optional().describe("Filter by role. Defaults to 'all'.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ role }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const profileId = await currentProfileId(supabase, ctx.getUserId());
    if (!profileId) {
      return {
        content: [{ type: "text", text: "No VeggieMeet profile yet \u2014 finish onboarding first." }],
        isError: true
      };
    }
    const r = role ?? "all";
    const { data: attendance } = await supabase.from("attendance").select("meetup_id, status, meetups(*)").eq("profile_id", profileId);
    const rows = (attendance ?? []).map((a) => a.meetups).filter(Boolean).filter((m) => {
      if (r === "hosting") return m.host_id === profileId;
      if (r === "attending") return m.host_id !== profileId;
      return true;
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { meetups: rows }
    };
  }
});

// src/lib/mcp/tools/join-meetup.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
var join_meetup_default = defineTool4({
  name: "join_meetup",
  title: "Join a meetup",
  description: "Join a VeggieMeet meetup as the signed-in user. Idempotent \u2014 joining an already-joined meetup succeeds silently.",
  inputSchema: {
    meetup_id: z4.string().describe("The meetup id (UUID) to join.")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ meetup_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const profileId = await currentProfileId(supabase, ctx.getUserId());
    if (!profileId) {
      return {
        content: [{ type: "text", text: "No VeggieMeet profile yet \u2014 finish onboarding first." }],
        isError: true
      };
    }
    const { error } = await supabase.rpc("join_meetup", { _meetup_id: meetup_id });
    if (error) {
      return {
        content: [{ type: "text", text: `Could not join: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: "Joined meetup. See you there \u{1F331}" }],
      structuredContent: { meetup_id, status: "joined" }
    };
  }
});

// src/lib/mcp/tools/list-my-connections.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_my_connections_default = defineTool5({
  name: "list_my_connections",
  title: "List my Veggie Network",
  description: "List the signed-in user's confirmed VeggieMeet connections (their Veggie Network).",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const me = await currentProfileId(supabase, ctx.getUserId());
    if (!me) {
      return {
        content: [{ type: "text", text: "No VeggieMeet profile yet." }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("friendships").select(
      "profile_a_id, profile_b_id, friends_since, status, first_meetup_id"
    ).or(`profile_a_id.eq.${me},profile_b_id.eq.${me}`);
    if (error) {
      return {
        content: [{ type: "text", text: `Failed: ${error.message}` }],
        isError: true
      };
    }
    const otherIds = (data ?? []).map(
      (f) => f.profile_a_id === me ? f.profile_b_id : f.profile_a_id
    );
    const { data: profiles } = otherIds.length ? await supabase.from("profiles").select("id, display_name, current_city").in("id", otherIds) : { data: [] };
    const rows = (data ?? []).map((f) => {
      const other = f.profile_a_id === me ? f.profile_b_id : f.profile_a_id;
      const p = (profiles ?? []).find((x) => x.id === other);
      return {
        connection: p ?? { id: other },
        friends_since: f.friends_since,
        status: f.status,
        first_meetup_id: f.first_meetup_id
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { connections: rows }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_my_profile_default = defineTool6({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's VeggieMeet profile: display name, city, interests, and community stats.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_my_profile");
    const row = Array.isArray(data) ? data[0] : data;
    if (error || !row) {
      return {
        content: [{ type: "text", text: "Profile not found." }],
        isError: true
      };
    }
    const projection = {
      id: row.id,
      display_name: row.display_name,
      bio: row.bio,
      current_city: row.current_city,
      interests: row.interests,
      is_active_host: row.is_active_host,
      meetups_hosted_count: row.meetups_hosted_count,
      meetups_attended_count: row.meetups_attended_count,
      onboarding_completed: row.onboarding_completed
    };
    return {
      content: [{ type: "text", text: JSON.stringify(projection, null, 2) }],
      structuredContent: projection
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bmlchfrhdcafyfysnfok";
var mcp_default = defineMcp({
  name: "veggiemeet-mcp",
  title: "VeggieMeet",
  version: "0.1.0",
  instructions: "Tools for VeggieMeet \u2014 a community for plant-based people to meet up in real life. Use these tools to browse upcoming meetups, look up meetup details, see the signed-in user's hosted and joined meetups, join meetups, and list their Veggie Network connections. All actions run as the signed-in VeggieMeet user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_upcoming_meetups_default,
    get_meetup_default,
    list_my_meetups_default,
    join_meetup_default,
    list_my_connections_default,
    get_my_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
