-- WO-145: extend the analytics allow-list with PWA update-health events.
-- Content-free vocabulary only (no tokens, profile data, messages or URLs).
CREATE OR REPLACE FUNCTION public.analytics_event_allowed(_event_name text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
SET search_path TO 'public'
AS $function$
  SELECT _event_name IN (
    'today_opened','community_home_opened','notifications_opened','you_opened',
    'account_deletion_blocked','account_deletion_completed','account_deletion_started',
    'auth_signin_success','auth_signup_started','auth_signup_success',
    'check_in_started_from_plans','community_impact_place_count_updated',
    'community_place_card_opened','community_place_check_in_failed',
    'community_place_check_in_started','community_place_check_in_succeeded',
    'community_place_detail_opened','community_place_directions_opened',
    'community_place_edit_blocked','community_place_edit_completed',
    'community_place_edit_google_checked','community_place_edit_opened',
    'community_place_edit_previewed','community_place_host_started',
    'community_place_identity_review_blocked','community_place_identity_review_cancelled',
    'community_place_identity_review_completed','community_place_identity_review_opened',
    'community_place_identity_review_started','community_place_meetup_opened',
    'community_place_operations_activity_loaded_more',
    'community_place_operations_attention_opened',
    'community_place_operations_filter_changed','community_place_operations_place_opened',
    'community_place_report_blocked','community_place_report_history_opened',
    'community_place_report_moderated','community_place_report_notification_opened',
    'community_place_report_owner_opened','community_place_report_started',
    'community_place_report_submitted','community_place_reverification_cancelled',
    'community_place_reverification_completed','community_place_reverification_queue_opened',
    'community_place_reverification_started','community_place_shared',
    'community_place_suggestion_failed','community_place_suggestion_owner_opened',
    'community_place_suggestion_promoted','community_place_suggestion_started',
    'community_place_suggestion_submitted','community_place_vegan_review_blocked',
    'community_place_vegan_review_cancelled','community_place_vegan_review_completed',
    'community_place_vegan_review_opened','community_place_vegan_review_started',
    'community_places_filter_changed','community_places_opened',
    'discovery_settings_saved','error_boundary_activated',
    'location_permission_result','meetup_check_in_blocked','meetup_check_in_completed',
    'meetup_check_in_started','meetup_community_place_opened',
    'meetup_community_place_selected','meetup_community_place_viewed',
    'meetup_completion_blocked','meetup_completion_completed','meetup_completion_started',
    'meetup_created','meetup_created_at_community_place','meetup_left_from_plans',
    'meetup_location_change_notification_opened','meetup_location_mode_selected',
    'meetup_location_review_opened','meetup_location_update_blocked',
    'meetup_location_update_completed','meetup_location_update_started',
    'member_blocked','member_reported','my_plans_opened',
    'notification_preference_changed','notification_permission_result',
    'offline_detected','onboarding_completed','onboarding_starting_action_chosen',
    'onboarding_step_completed','onboarding_step_viewed',
    'place_suggestion_history_opened','place_suggestion_notification_created',
    'place_suggestion_notification_opened','plan_opened','profile_visibility_changed',
    'reconnect_completed','request_failed','settings_opened','settings_profile_updated',
    'sign_out_completed','supported_place_card_opened','supported_places_explore_clicked',
    'supported_places_opened',
    'op_read_failed','op_mutation_failed','op_auth_failed','op_realtime_failed',
    'op_deeplink_failed','op_app_boot_failed',
    'beta_feedback_opened','beta_feedback_submitted','beta_feedback_failed',
    'owner_beta_operations_opened','owner_beta_feedback_status_updated',
    'owner_community_place_operations_opened',
    'follow_up_prompt_shown','follow_up_opened','follow_up_dismissed',
    'host_opened','meet_next_opened','network_opened',
    'connection_request_sent','connection_request_accepted','meetup_joined',
    'auth_password_reset_requested','auth_password_reset_success',
    'auth_password_reset_failed','auth_signin_failed',
    'today_place_curation_opened','today_place_featured','today_place_unfeatured',
    'today_place_hidden','today_place_restored','today_place_reordered',
    'meetup_add_to_calendar',
    -- WO-144 multi-select Veggie Network invitations
    'meetup_invite_sheet_opened','meetup_invitations_sent','meetup_invitations_failed',
    -- WO-145 PWA update lifecycle health
    'app_update_detected','app_update_prompt_shown','app_update_postponed',
    'app_update_activation_requested','app_update_blocked_unsaved',
    'app_update_controller_changed','app_update_reload_completed',
    'app_update_failed','app_update_build_mismatch'
  );
$function$;